### ISSUE TITLE
Add git tags for gopkg?

### ISSUE THREAD

**Issue by natebrennand** [underarmour/dynago#6]
Hi,
We're using dynago for [a project](https://github.com/Clever/who-is-who) and have really enjoyed the API in comparison to aws-go. Thank you open sourcing this project!
It would be very helpful for us if you could add branch tags so that we could use a versioned import from [gopkg](http://labix.org/gopkg.in). It just involves adding tags for versions, like `v1.0.0`. We'd rather avoid Godep if possible.
Thanks for your consideration.

**Comment by crast** [comment]
It would also require rewriting the internal package imports to be gopkg.in as the canonical path, but I'm willing to do that for the sake of versioning guarantees. 

I'll get that in this weekend.

**Comment by natebrennand** [comment]
Thank you for adding gopkg!
